# Generated by Django 5.2.8 on 2025-11-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('agent', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents_cats.spycats')),
            ],
        ),
        migrations.CreateModel(
            name='SpyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='agents_missions.spymission')),
            ],
        ),
    ]
