# Generated by Django 5.2.8 on 2025-11-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_cats', '0001_initial'),
        ('agents_missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spymission',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='agents_cats.spycats'),
        ),
    ]
