# Generated by Django 5.2.8 on 2025-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpyCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.FloatField(default=0.0)),
                ('breed', models.CharField(max_length=100)),
                ('salary', models.FloatField(default=0.0)),
            ],
        ),
    ]
